source 'https://github.com/CocoaPods/Specs.git'

workspace '../XNGMarkdownParser'
xcodeproj 'Example.xcodeproj'
plugin 'slather'

use_frameworks!

target "Example" do
  pod 'XNGMarkdownParser', :path => '..'
end

target "ExampleTests" do
  pod 'Expecta', '~> 1.0'
  pod 'FBSnapshotTestCase', '= 1.7'
end
