source 'https://github.com/CocoaPods/Specs.git'

workspace '../XNGMarkdownParser'
xcodeproj 'Example.xcodeproj'

target "Example" do
  pod "XNGMarkdownParser", :path => "../XNGMarkdownParser.podspec"
end

target "ExampleTests" do
  pod 'Expecta', '~> 0.3.1'
  pod 'FBSnapshotTestCase'
end

require 'slather'
Slather.prepare_pods(self)
