source 'https://github.com/CocoaPods/Specs.git'

workspace '../XNGMarkdownParser'
xcodeproj 'Example.xcodeproj'
plugin 'slather'

target "Example" do
  pod 'XNGMarkdownParser', :path => '..'
end

target "ExampleTests" do
  pod 'Expecta', '~> 0.3.1'
  pod 'FBSnapshotTestCase'
end
